version: "{build}"
build: off
deploy: off
cache:
  - "%LOCALAPPDATA%\\Yarn"
branches:
  only:
    - main
  except:
    - gh-pages
matrix:
  fast_finish: true
environment:
  matrix:
    - nodejs_version: 14
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install
test_script:
  - node --version
  - yarn --version
  - cmd: yarn lint
  - cmd: yarn test
  - cmd: yarn build
