version: '{build}'
build: off
deploy: off
cache:
  - .yarn -> package.json
  - .yarn -> yarn.lock
branches:
  only:
    - master
    - /^greenkeeper/.*$/
  except:
    - gh-pages
matrix:
  fast_finish: true
environment:
  matrix:
    - nodejs_version: 10
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install
test_script:
  - node --version
  - yarn --version
  - cmd: yarn lint
  - cmd: yarn test
  - cmd: yarn build
